Feat/Add more comprehensive typing
studio-freight/react-lenis pull request #23
Opened 2023-08-08 22:31 UTC by balraj-johal

2023-08-30 08:39 UTC, cemreinanc requested changes
Hey! I got the same type errors and tried your branch. Generally works well but I noticed a couple of type mismatches in `scrollTo` function. Suggested fixes to them.

Thanks!

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {ScrollToOptions} options
```suggestion
 * @param {ScrollToParams} [options]
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {number} offset equivalent to scroll-padding-top
```suggestion
 * @property {number} [offset] equivalent to scroll-padding-top
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {number} lerp animation lerp intensity
```suggestion
 * @property {number} [lerp] animation lerp intensity
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {number} duration animation duration (in seconds)
```suggestion
 * @property {number} [duration] animation duration (in seconds)
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {EasingFunction} easing animation easing
```suggestion
 * @property {EasingFunction} [easing] animation easing
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {boolean} immediate ignore duration, easing and lerp
```suggestion
 * @property {boolean} [immediate] ignore duration, easing and lerp
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {boolean} lock whether or not to prevent the user from scrolling until the target is reached
```suggestion
 * @property {boolean} [lock] whether or not to prevent the user from scrolling until the target is reached
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {boolean} force reach target even if instance is stopped
```suggestion
 * @property {boolean} [force] reach target even if instance is stopped
```

2023-08-30 08:39 UTC, cemreinanc commented on src/index.jsx
> + * @param {CallbackFunction} onComplete called when the target is reached
```suggestion
 * @property {CallbackFunction} [onComplete] called when the target is reached
```

2023-08-30 11:03 UTC, balraj-johal commented
@cemreinanc Thanks for your input! All oversights by me, appreciate it!

2023-08-30 11:04 UTC, balraj-johal commented
@clementroche This PR adding more comprehensive type definitions to the index.jsx file should be ready for review if you get the time :)

2023-09-23 02:24 UTC, arzafran approved these changes
lgtm

2023-09-23 02:25 UTC, merged